<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNaxHAqM\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNaxHAqM/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNaxHAqM.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNaxHAqM\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerNaxHAqM\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'NaxHAqM',
    'container.build_id' => 'd61ad74f',
    'container.build_time' => 1652409642,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNaxHAqM');
