<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIzuBQGA\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIzuBQGA/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIzuBQGA.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIzuBQGA\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIzuBQGA\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IzuBQGA',
    'container.build_id' => 'a73e2d9c',
    'container.build_time' => 1651794390,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIzuBQGA');
