<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGq7oMjo\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGq7oMjo/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGq7oMjo.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGq7oMjo\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGq7oMjo\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Gq7oMjo',
    'container.build_id' => 'd4f78bee',
    'container.build_time' => 1652134274,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGq7oMjo');
